version: "3"
services:
  mongo:
    container_name: discord-rss-mongodb
    restart: on-failure:5
    command: mongod --port 27017
    # Uncomment below to hide mongo logs
    #logging:
    #  driver: none
    image: mongo:latest
    volumes:
      - 'mongo:/data/db'
    expose:
      - 27017
  discordrss:
    container_name: discord-rss
    restart: on-failure:10
    build: .
    links:
      - mongo
    environment:
      - DRSS_BOT_TOKEN=drss_docker_token
      - DRSS_DATABASE_URI=mongodb://mongo/rss

volumes:
  mongo:
